### ISSUE TITLE
What are all the needed dependencies?

### ISSUE THREAD

**Issue by woodworker** [NoMoKeTo/c3nav#1]
i did just what the readme said
clone and then run pip

i needed to install already
- `libpng++-dev`
- `libfreetype6-dev`
- `liblapack-dev`

now the installation process is complaining about a not installed Fortran

```
don't know how to compile Fortran code on platform 'posix'

building 'dfftpack' library

error: library dfftpack has Fortran sources but no Fortran compiler found
```

you maybe want to inform about all the dependencies needed to actually run you pip installation process

**Comment by codingcatgirl** [comment]
Those dependencies come from the dependencies. Installing scipy using pip is not fun – especially as the error messages really are not helpfull. So, it's not “my fault” and i think they should write their pip packages better. Maybe i will someday add information about it to the README but it's not too easy to figure out the complete list.

What you can do is search for the packages on some other package-manager (e.g. apt-get) to install the python packages from there or just install the dependencies (e.g. apt-get build-dep python3-scipy).

**Comment by NoMoKeTo** [comment]
f4c7ed64b208f6cd3d0372fa77de9146f9812b97

**Comment by codingcatgirl** [comment]
6b1abc5d585c3971f438069c5943db3c5377c754
