### ISSUE TITLE
Rust Assembly

### ISSUE THREAD

**Issue by klingtnet** [NoMoKeTo/c3nav#19]
I hope the coordinates are correct, the assembly is near the NOC.
Location: [o1:726:537](https://c3nav.de/o1:726:537)

**Comment by codingcatgirl** [comment]
i don't thin that can be right… that's were the  kinkygeeks are…?

**Comment by codingcatgirl** [comment]
done (coordinates form other issue): 76a45b63f4fefef651a771f2326e03e4a3e16374
