### ISSUE TITLE
Link with coordinates of a point clicked on the map to open a zoomable map with highlighted coordinates

### ISSUE THREAD

**Issue by ElLutzo** [NoMoKeTo/c3nav#32]
Add a way to link the coordinates of a point clicked on the map to open a zoomable map with the coordinates highlighted on the map.
1. Add a Button or Link named like "Map" that just opens the zoomable map.
2. When the user clicked on the map, show a copyable link with the coordinates of the point clicked on the map like: https://c3nav.de/pos0:456:466
3. When the user clicks on the link, a zoomable map with the point identfied by the coordinates is highlighted.

**Comment by codingcatgirl** [comment]
this is more or less the same as #5.

i will do it when i have time to implement it, but there will be definetely nothing zoomable because i don't want include another fancy library for that at the moment or implement it myself.
