### ISSUE TITLE
AAA & SDF-Kurs

### ISSUE THREAD

**Issue by buckket** [NoMoKeTo/c3nav#37]
Hey there,

just wanted to share the coordinates of the [AAA](https://events.ccc.de/congress/2015/wiki/Assembly:AAA) and [SDF-Kurs](https://events.ccc.de/congress/2015/wiki/Assembly:SDF-Kurs) assemblies, so that they can be added to the system.

AAA: `1:267:514`
SDF-Kurs: `0:465:384`

Thanks!

**Comment by codingcatgirl** [comment]
Just added them, thanks :)
