### ISSUE TITLE
Use elevator(s) in fastest mode

### ISSUE THREAD

**Issue by Manu1400** [NoMoKeTo/c3nav#41]
https://c3nav.de/?steps=yes&stairs=yes&escalators=yes&elevators=yes&force-e=1&force-i=1&s-default=160&s-elevator=20&s-stairs-up=130&s-stairs-down=160&s-escalator-up=160&s-escalator-down=160&route=fast&o=tea&d=0%3A648%3A614
- "Your Route 279.4m / 2min 54s" in fastest route
- Your Route 93.7m / 1min 38s with "shortest route"

**Comment by codingcatgirl** [comment]
interesting. i'll have to take a look at that.

**Comment by codingcatgirl** [comment]
well, the result wasn't wrong but the total duration was :)
