### ISSUE TITLE
Feature: Display POI on map

### ISSUE THREAD

**Issue by Feuermurmel** [NoMoKeTo/c3nav#5]
I think it would be great if it was possible to search for a POI and display its location on the map without planning a route or needing to declare a starting position.

**Comment by codingcatgirl** [comment]
yeah, propably usefull, but i don't think i will find the time during congress to come up with an UI way for that…

**Comment by codingcatgirl** [comment]
847c88c53a910f7d26ef73897bb3238a224f8d62 done.
