### ISSUE TITLE
"de" language button inaccessible on narrow displays

### ISSUE THREAD

**Issue by Feuermurmel** [NoMoKeTo/c3nav#7]
E.g. on an iPhone 4, the page is rendered so narrowly that the button to change the language to German is inaccessible behind the "Fork me on GitHub" banner.

![2015-12-26 17 21 21](https://cloud.githubusercontent.com/assets/50332/12007144/787d938c-abf7-11e5-8280-7d8d7d3d6ee7.png)

**Comment by codingcatgirl** [comment]
it can also be found on the bottom of the page :)
