### ISSUE TITLE
date flow is unclear

### ISSUE THREAD

**Issue by ThomasWaldmann** [NoMoKeTo/c3nav#8]
ok, i am sitting here at the python assembly.

how do i get an assembly on the map and navigation to it working?

could that data flow info be put on the frontpage?

also: I am confused with the map (png), it does not seem to match reality precisely. can i use c3nav to determine what the system thinks where I am and submit it to you with the name of the assembly?

**Comment by codingcatgirl** [comment]
the map is accurate. you can send me your coordinates (you can get them by selecting from mac) along with your assembly title and i'll add it.
